language: python
python:
        - 2.7
        - 3.6
dist: trusty
cache: pip

### Don't need this at the moment
# before_install:
#   # Bring pip up to date
#   - pip install --upgrade pip setuptools wheel
#   - pip install --only-binary=numpy,scipy numpy scipy
#   - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support

install:
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'

script:
  - py.test . --cov spinn_utilities
  # Code quality check
  - flake8 spinn_utilities unittests
  - cd doc/source
  - sphinx-build -W -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -W -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -W -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
